### ISSUE TITLE
Support PostgreSQL RETURNING (column1, column2, ...) clause in INSERT, UPDATE and DELETE

### ISSUE THREAD

**Issue by kyshnirev** [runner-mei/GoBatis#3]
PostgreSQL database has the [RETURNING](https://www.postgresql.org/docs/current/dml-returning.htmll "postgresql 11 docs") clause, it is very useful.

Currently the *CreateUser* method can return only ID of inserted row:

```
type Users interface {
    CreateUser(name string): (int64, error)
}
```

I want create method *CreateUser* with returning struct pointer and error.
Support "returning" clause will able to write more power SQL queries,  something like this:

users.go
```
type User struct {
    TableName struct {} `db:"users"`
    ID int64 `db:"id"`
    Created time.Time `db:"created"`
    Name string `db:"login"`
}

type Users interface {
    CreateUser(name string): (*User, error)
}
```

users.xml
```
<bogatis>
  <insert id="Users.CreateUser">
    INSERT INTO users (id, created, name) 
    VALUES (nextval('seq_users_id'), now(), #{name})
    RETURNING id, created, name
  </insert>
</bogatis>
```

**Comment by runner-mei** [comment]
fix it on v1.1.5
