### ISSUE TITLE
生成出来的文件中, 缺少context的import

### ISSUE THREAD

**Issue by zohar-soul** [runner-mei/GoBatis#4]
是不是模板漏写了?

**Comment by runner-mei** [comment]
模板不管这个， 我工具中生成完后会自动调用 goimports,   少 import 你看看是不是别的问题导致的

**Comment by zohar-soul** [comment]
还有个问题是, 对于mysql 5.7新的json类型的支持是怎么样的啊?

**Comment by runner-mei** [comment]
我没有试过， 我试试

**Comment by zohar-soul** [comment]
还有就是事务怎么用的啊? 看了下 session_test.go 没太理解怎么和 mapper 结合起来?

可以加我微信: tencent_wechat_id_g ,发个红包 sponsor 支持一下.

**Comment by runner-mei** [comment]
我增加了一个文档 https://runner-mei.github.io/GoBatis/#/tx

**Comment by zohar-soul** [comment]
@runner-mei 非常感谢.

**Comment by zohar-soul** [comment]
@runner-mei 
  // ...
  tx := db.Begin()
  defer tx.Rollback()
  ctx := gobatis.WithTx(context.Background(), tx)

这里面的db和gobatis指的是什么啊?

**Comment by runner-mei** [comment]
db   就是 *sql.DB 对象啊https://golang.google.cn/pkg/database/sql/#DB

gobatis.WithTx 就是我库的一个方法啊 https://github.com/runner-mei/GoBatis/blob/master/connection.go#L92

**Comment by zohar-soul** [comment]
> db 就是 *sql.DB 对象啊https://golang.google.cn/pkg/database/sql/#DB
> 
> gobatis.WithTx 就是我库的一个方法啊 https://github.com/runner-mei/GoBatis/blob/master/connection.go#L92

👌🏻, 我以为只补充了文档, 没注意代码也有变动.

**Comment by runner-mei** [comment]
针对这两个方法，增加了两个完整的例子

https://github.com/runner-mei/GoBatis/blob/master/example/transaction_test.go
