### ISSUE TITLE
IsUnsafe = true 的时候，无法工作

### ISSUE THREAD

**Issue by zliu74** [runner-mei/GoBatis#6]
GetXXX() 到一个 struct的时候，说不是指针无法scan

**Comment by runner-mei** [comment]
没有理解你的意思， 能给一个具体的例子么？

**Comment by zliu74** [comment]
factory, err := gobatis.New(&gobatis.Config{DriverName: "mysql",
		DataSource: "user:pass@tcp(localhost:3306)/test",
		**IsUnsafe:   true,**
	})

	roleDao := example.NewRoleDao(factory.SessionReference())
	role1, err := roleDao.Get(1)

**Comment by runner-mei** [comment]
你的  RoleDao 以及 Get 方法怎么定义 的
还有 Role 对象怎么定义的

**Comment by zliu74** [comment]
就用你的example里的就可以重现。
只要加了 IsUnsafe:   true,
scan到任何struct 都会失败

**Comment by runner-mei** [comment]
我开启了 IsUnsafe=true 了，没有问题啊
这是源码
https://github.com/runner-mei/GoBatis/blob/d35affa45f7870f8fc2201ee57b025a8f20fcc9a/tests/session.go#L1458

这是运行结果
https://github.com/runner-mei/GoBatis/actions/runs/1542523104

**Comment by runner-mei** [comment]
问题找到了， 当数据库为 oracle 或 达梦 时会出这个错。

**Comment by runner-mei** [comment]
用 mysql 时如果字段有引号时，可能也会出这个问题
